### ISSUE TITLE
Add gunicorn and nginx to docker-compose services for deployment

### ISSUE THREAD

**Issue by GoelJatin** [HydPy/meetup-manager#15]
The idea is to start using gunicorn and nginx for deployment from the initial stages instead of relying on django development server

**Comment by sreevardhanreddi** [comment]
Can I work on this?

**Comment by GoelJatin** [comment]
I started on this, but maybe we can do pair programming on this?

If you agree I can setup a Google Meet and we can start from there. Let me know your opinion.
